### ISSUE TITLE
自用的

### ISSUE THREAD

**Issue by Vsoultura** [Milesians/ApexLegendsLogiLua#1]
现在自用的失效了是为什么

**Comment by Milesians** [comment]
需要测试Ghub有没有生效，有可能你的steam是以管理员启动的，而Ghub不是

**Comment by Vsoultura** [comment]
你是在自己写lua吗，我也是程序员 加个v介意不 Libre-ame

**Comment by Milesians** [comment]
> 现在自用的失效了是为什么

我已经删除了你的上一个回复，不要再网上留下你的个人信息，需要联系可以添加我的TG @Milesians
